/** Fresh-process re-acceptance of saved answers and source clocks, without media regeneration. */
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {bind,formal,sha} from '../../../evals/clip_composition/run_candidate_discovery_digest_skill_e2e_v001.mts';
import {buildUnseenDiscoveryRequestV001,validateUnseenDiscoveryV001,selectUnseenCandidatesV001} from '../../../evals/clip_composition/unseen_material_thin_plan_v001.mts';
import {buildSelectionRequestV001} from '../../../evals/clip_composition/candidate_selection_validation_v001.mts';
import {runCandidateDiscoveryV001} from '../../../runner/src/skills/candidate-discovery-v001.ts';
import {runCandidateSelectionV001} from '../../../runner/src/skills/candidate-selection-v001.ts';
import {runInternalRetentionV001} from '../../../runner/src/skills/candidate-internal-retention-v001.ts';
import {validateInternalRetentionProvenanceV001,resolveInternalRetentionV001} from '../../../evals/clip_composition/candidate_internal_retention_validation_v001.mts';
import {validatePresentationBaseMediaSegmentPlanV002} from '../../../evals/clip_composition/presentation_base_media_build_v003.mjs';
const R='runtime/artifacts/selection-structure-improvement-20260930-v001',O='runtime/artifacts/digest-new-material-20260926-v001',load=async(p:string)=>JSON.parse(await readFile(p,'utf8'));
const proposal=await load('docs/reports/selection-structure-improvement-20260930/proposal-v001.json'),utterances=await load(O+'/utterances.json'),transcript=await load(O+'/transcript.json'),intent=await load(R+'/production-intent.json');
let verifiedRefs=0;for(const ref of proposal.bindings){assert.equal(sha(await readFile(ref.path)),ref.fileSha256,'bound input changed: '+ref.path);verifiedRefs++}
const d=await load(R+'/discovery-plan.json'),ctx:any={plan:d,planBinding:bind(R+'/discovery-plan.json',d),thinPlan:intent,utterances,transcript};
const req=await load(R+'/candidate-request.json'),resp=await load(R+'/candidate-response.json');assert.deepEqual(buildUnseenDiscoveryRequestV001(ctx),req);
const result=await runCandidateDiscoveryV001(req.input,async()=>resp.answer);assert.deepEqual(result,await load(R+'/candidate-result.json'));const discovery=validateUnseenDiscoveryV001(ctx,req,resp,result);assert.deepEqual(discovery.candidateSet,await load(R+'/candidate-set.json'));
const sp=await load(R+'/selection-plan.json'),sc:any={...ctx,plan:sp,planBinding:bind(R+'/selection-plan.json',sp),candidateSet:discovery.candidateSet};const sr=await load(R+'/selection-request.json'),ss=await load(R+'/selection-response.json');assert.deepEqual(buildSelectionRequestV001(sc),sr);
const selectionResult=await runCandidateSelectionV001(sr.input,async()=>ss.answer);assert.deepEqual(selectionResult,await load(R+'/selection-result.json'));const selected=selectUnseenCandidatesV001(sc,sr,ss,selectionResult);assert.deepEqual(selected.adoption,await load(R+'/selection-adoption.json'));
const rr=await load(R+'/retention-request.json'),rs=await load(R+'/retention-response.json'),byU=new Map(utterances.utterances.map((u:any)=>[u.utteranceId,u])),byAtom=new Map(transcript.segments.map((s:any)=>[s.id,s]));
assert.equal(rr.input.taskDescription.startsWith(intent.productionIntent),true);assert.deepEqual(rr.input.candidates,selected.adoption.adoptedCandidates.map((p:any)=>({candidateId:p.candidateId,title:p.title,highlightReason:p.judgment.reason,utterances:p.includedUtteranceIds.map((id:string)=>({utteranceId:id,atoms:(byU.get(id)as any).sourceSegmentIds.map((a:number)=>({sourceSegmentId:a,text:(byAtom.get(a)as any).text}))}))})));
const retentionResult=await runInternalRetentionV001(rr.input,async()=>rs.answer);assert.deepEqual(retentionResult,await load(R+'/retention-result.json'));const token=validateInternalRetentionProvenanceV001(rr,rs,retentionResult,rr.input);
const observed={transcriptBinding:d.request.transcript,units:transcript.segments.filter((a:any)=>a.endMs>a.startMs).map((a:any)=>({unitId:'gpu-fragment-'+a.id,startMs:a.startMs,endMs:a.endMs,startBoundary:{after:a.id},endBoundary:{before:a.id},startTimeRole:'gpu-aligned-source-fragment',timeOrigin:'full-source-gpu-stt'}))};const retention=resolveInternalRetentionV001(token,selected.adoption.adoptedCandidates,[observed]);assert.deepEqual(retention,await load(R+'/retention-validation.json'));assert.equal(retention.status,'resolved');
const edit=await load(R+'/edit-plan.json');assert.deepEqual(edit.segments,retention.segments.map((p:any)=>({candidateId:p.candidateId,segmentId:p.segmentId,sourceStartMs:p.sourceStartMs,sourceEndMs:p.sourceEndMs,sourceSegmentIds:p.sourceSegmentIds})));
const m=(await load(O+'/base-attempt-002/source-media-inspection.json')).media;const clock=validatePresentationBaseMediaSegmentPlanV002(edit.segments.map(({sourceStartMs,sourceEndMs}:any)=>({sourceStartMs,sourceEndMs})),{fps:m.fps,decodedFrameCount:m.decodedFrameCount,logicalFrameCount:m.logicalFrameCount,presentationOffsetMs:m.videoClock.presentationOffsetMs},m.audioClock);assert.equal(clock.status,'passed');assert.deepEqual(clock,await load(R+'/clock-resolution.json'));
const ids=retention.segments.flatMap((s:any)=>s.sourceSegmentIds);assert.equal(new Set(ids).size,ids.length);for(const [i,p]of retention.segments.entries()){assert.deepEqual(proposal.selectedSpans[i].sourceFragmentRange,[p.sourceSegmentIds[0],p.sourceSegmentIds.at(-1)]);assert.equal(proposal.selectedSpans[i].text,p.sourceSegmentIds.map((a:number)=>(byAtom.get(a)as any).text).join(''));assert.deepEqual(proposal.selectedSpans[i].clock,clock.mappings[i])}
for(const [label,ps]of Object.entries({firstDraft:(await load(O+'/edit-plan.json')).segments,sevenB:(await load('runtime/artifacts/digest-structure-20260929-v001/structure-resolution.json')).selectedSegments}) as any){const prior=new Set(ps.flatMap((p:any)=>p.sourceSegmentIds));const current=new Set(ids);for(const [kind,expected]of Object.entries({added:ids.filter((a:number)=>!prior.has(a)),removed:[...prior].filter(a=>!current.has(a)),unchanged:ids.filter((a:number)=>prior.has(a))})){const actual=proposal.differences[label][kind].flatMap((p:any)=>Array.from({length:p.sourceFragmentRange[1]-p.sourceFragmentRange[0]+1},(_,i)=>i+p.sourceFragmentRange[0]));assert.deepEqual(actual,[...expected as number[]].sort((a,b)=>a-b))}}
assert.equal(proposal.humanAdoption,false);assert.equal(proposal.outlineChoice,null);assert.equal(proposal.independentReviewResponse.comparison.decision,'今回一案では不採用。採用済み9区間は変更しない。');
const report={status:'passed',processId:process.pid,verifiedRefs,sourceUtterances:utterances.utterances.length,candidates:discovery.candidateSet.candidates.length,adopted:selected.adoption.adoptedCandidates.length,retainedSpans:retention.segments.length,retainedFragments:ids.length,outputFrames:clock.mappings.at(-1).outputEndFrame,requestRebuilt:true,discoverySelectionRetentionReaccepted:true,sourceCoverageAndClockRecomputed:true,differencesRecomputed:true,humanAdoption:false,outlineChoice:null,proposalSha256:sha(await readFile('docs/reports/selection-structure-improvement-20260930/proposal-v001.json'))};await writeFile(R+'/independent-acceptance-reread-v001.json',formal(report),{flag:'wx'});console.log(JSON.stringify(report));
